polyfy/polylith

.circleci/config.yml
bases/deployer-cli/src/polylith/clj/core/deployer_cli/core.clj
build.sh
components/deployer/src/polylith/clj/core/deployer/core.clj
components/deployer/src/polylith/clj/core/deployer/interface.clj
components/workspace-clj/src/polylith/clj/core/workspace_clj/core.clj
components/workspace/test/polylith/clj/core/workspace/text_table/ws_table_test.clj
deps.edn
development/src/dev/jocke.clj
environments/deployer/deps.edn
environments/migrator/deps.edn
environments/migrator/pom.xml
environments/poly/deps.edn
environments/poly/pom.xml
readme.md
scripts/build-migrator-uberjar.sh
scripts/build-uberjar.sh

* Added CircleCI config.
* Added deployer component.
* Added deployer-cli base.
* Added deployer environment.

Setup CircleCI

---

.circleci/config.yml
components/api/src/polylith/clj/core/api/core.clj
components/api/src/polylith/clj/core/api/interface.clj
components/deployer/src/polylith/clj/core/deployer/core.clj
environments/api/pom.xml
environments/poly/deps.edn
environments/poly/pom.xml

* Added stable point to workspace function. 
* Changed keys to be passed in as keyword list.
* Started using environments-to-deploy function. 
* Included api environment as deployable.
* Updated pom.xml files for poly and api.
* Updated circleci configuration.

Deployer improvements

---

components/api/src/polylith/clj/core/api/core.clj
components/change/src/polylith/clj/core/change/core.clj
components/change/src/polylith/clj/core/change/interface.clj
components/git/src/polylith/clj/core/git/core.clj
components/git/src/polylith/clj/core/git/interface.clj

* Changed from last build to previous build.
* Changed from with-last-build-changes to with-previous-build-changes.

Deployer fix

---

components/workspace-clj/test/polylith/clj/core/workspace_clj/environment_test.clj

Fixed failing test by removing :size keys from the map that read files from disk.

Fixed failing test

---

components/creator/src/polylith/clj/core/creator/workspace.clj
components/creator/test/polylith/clj/core/creator/workspace_test.clj
components/help/src/polylith/clj/core/help/create_workspace.clj
components/test-runner/src/polylith/clj/core/test_runner/core.clj
readme.md

* Updated the doc: Context (new), Naming (new), Mix Languages (new) + more.
* Set correct :deps/root in deps.edn when creating a workspace. 
* Changed message to "Running tests from...".

Update doc 11

---

.circleci/config.yml
.idea/runConfigurations/REPL.xml
components/deployer/src/polylith/clj/core/deployer/core.clj
environments/api/deps.edn
environments/api/pom.xml
environments/core/deps.edn
environments/migrator/deps.edn
environments/migrator/pom.xml
environments/poly/deps.edn
environments/poly/pom.xml
scripts/build-skinny-jar.sh

* Use skinny jars to deploy to clojars.
* Added github url and description to pom.xml.
* Created separate CircleCI workflow for deployment.

Clojars deployment fix

---

.circleci/config.yml
environments/api/pom.xml
environments/migrator/pom.xml
environments/poly/pom.xml

* Updated artifact versions and descriptions.
* Do not mark as stable on branches other than master.

Alpha2 release

---

components/version/src/polylith/clj/core/version/interface.clj

* Updated poly-git-sha to be419d4

Updated poly-git-sha to be419d4

---

components/creator/src/polylith/clj/core/creator/workspace.clj
components/creator/test/polylith/clj/core/creator/workspace_test.clj
components/migrator/src/polylith/clj/core/migrator/core.clj
components/version/src/polylith/clj/core/version/interface.clj

0.1.0-alpha3 release

---

components/command/src/polylith/clj/core/command/cmd_validator/core.clj
components/command/src/polylith/clj/core/command/cmd_validator/create.clj
components/command/src/polylith/clj/core/command/cmd_validator/executable.clj
components/command/src/polylith/clj/core/command/core.clj
components/command/src/polylith/clj/core/command/create.clj
components/command/test/polylith/clj/core/command/cmd_validator/core_test.clj
components/command/test/polylith/clj/core/command/cmd_validator/executable_outside_ws_test.clj
projects/poly/deps.edn

* Fixed a bug in the validation that allowed commands to be executed outside the workspace.
* Ensured the 'command' tests are executed from the poly project.

Validation bug

---

.circleci/config.yml
components/version/src/polylith/clj/core/version/interface.clj
readme.md

- Fixed incremental tests in CI config.
- Updated version number to 0.1.0-alpha4.

Release 0.1.0 alpha4

---

readme.md

* Updated to correct links to wiki from readme.

Updated to correct links to wiki from readme.

---

doc/ci-and-deployment.md

Updated links.

---

doc/ci-and-deployment.md

Updated links (second try).

---

components/version/src/polylith/clj/core/version/interface.clj
doc/commands.md
readme.md

- Updated version and references to it on documentation.

Alpha5 Release

---

components/creator/src/polylith/clj/core/creator/workspace.clj
components/creator/test/polylith/clj/core/creator/workspace_test.clj
example/sections/workspace/deps.edn
readme.md

* Added instructions on how to add Polylith Tool as a dependency.
* Added instructions on how to use other Polylith artifacts as a dependency.
* Replaced `LATEST` with `INSERT_LATEST_SHA_HERE`.

Installation Instructions

---

readme.md

Clarified the instructions for how to switch profiles in the REPL.

Clarified the instructions for how to switch profiles in the REPL.

---

readme.md

Hello
Found a small typeo when going over the readme.

fix typeo in readme

---

bases/poly-cli/src/polylith/clj/core/poly_cli/core.clj
components/api/src/polylith/clj/core/api/core.clj
components/change/src/polylith/clj/core/change/entity.clj
components/common/src/polylith/clj/core/common/core.clj
components/deps/src/polylith/clj/core/deps/interface_deps.clj
components/file/src/polylith/clj/core/file/interface.clj
components/git/src/polylith/clj/core/git/interface.clj
components/test-runner/src/polylith/clj/core/test_runner/core.clj
components/util/src/polylith/clj/core/util/core.clj
components/util/src/polylith/clj/core/util/interface.clj
components/validator/src/polylith/clj/core/validator/m101_illegal_namespace_deps.clj
components/validator/src/polylith/clj/core/validator/m105_illegal_name_sharing.clj
components/workspace-clj/src/polylith/clj/core/workspace_clj/bases_from_disk.clj
components/workspace-clj/src/polylith/clj/core/workspace_clj/definitions.clj
components/workspace-clj/src/polylith/clj/core/workspace_clj/interface.clj
components/workspace-clj/src/polylith/clj/core/workspace_clj/interface_defs_from_disk.clj
components/workspace/src/polylith/clj/core/workspace/interfaces.clj
components/ws-explorer/src/polylith/clj/core/ws_explorer/interface.clj

fixed clj-kondo warnings about the misplaced docstrings

fix misplaced docstrings

---

deps.edn

Fix comment in deps.edn
